### ISSUE TITLE
Suggestion about CI via github actions

### ISSUE THREAD

**Issue by mert-kurttutan** [kadirnar/yolov7-pip#1]
Hi Kadir,

I like idea of packaging some of the repositories for deep learning models.
Did you consider creating CI pipeline that updates/gives warning whenever there is an important change in the original yolov7 repo, (e.g. using Github Actions)?

I realized that there has not been important changes in the source code of yolov7. But, having at least notification for important (i.e. changes in the important directories) changes in the original repo would be beneficial.

This suggestion applies to your other repos that creates python packages for deep learning models

P.S. I am using English in case someone else wants to understand :)

**Comment by kadirnar** [comment]
Hello @mert-kurttutan ,

Can you show an example repo? Is this like something?
https://github.com/fcakyon/yolov5-pip/blob/main/.github/workflows/ci.yml

**Comment by mert-kurttutan** [comment]
I meant more like the followings:
- https://stackoverflow.com/questions/65499626/trigger-github-actions-if-push-in-another-repo
- https://stackoverflow.com/questions/65370859/github-action-trigger-on-another-repo-update-push-pull-request?noredirect=1&lq=1

The first one uses cron scheduler that essentially check the other repo on a daily basis to see if there is any update. Second one uses webhook via repository_dispatch trigger.

It seems that the solutions are not super clear. At this point, I have not tried this myself. I have a project to try it on. I can let you know about my experiments.

I think in the link you sent, it does CI without listening to the original repo of the model. Here, I suggest that you listen to the original repo of the YOLO model and check for any updates.

**Comment by mert-kurttutan** [comment]
I also found another discussion in case you are curious
- https://github.com/orgs/community/discussions/26323

**Comment by kadirnar** [comment]
Thank you for the information. I don't have much knowledge about package managers. I don't think there will be a problem because Yolov7 is no longer receiving updates. If you create an application using the method you mentioned, I can try it out. I am planning to open a pip repository for Yolov6 in the near future. I can work on this for Yolov6.

**Comment by mert-kurttutan** [comment]
Yeah, sure.
That is why I said important changes (maybe an update change model config, the way its doing inference for whatever reason:))
In any case, having an automated way to be notified about your source model would be beneficial.
I will let you know once I experimented on it. :)
