### ISSUE TITLE
any plans to include mask, and pose stuff? 

### ISSUE THREAD

**Issue by cagbal** [kadirnar/yolov7-pip#10]
original v7 repo provided mask and pose detection as well, any plans to include them?

**Comment by kadirnar** [comment]
> original v7 repo provided mask and pose detection as well, any plans to include them?

No. I don't think because yolov5/8 models are more successful. I can recommend this library for segmentation.
https://github.com/open-mmlab/mmsegmentation

**Comment by cagbal** [comment]
Thanks for the answer. Closing the issue then.
